export const cannedResponses = [
  "nada",
  "zip",
  "zilch",
  "nope",
  "nah",
  "no",
  "negative",
  "not happening",
  "absolutely not",
  "no chance",
  "not a chance",
  "never",
  "not today",
  "hard pass",
  "pass",
  "denied",
  "rejected",
  "declined",
  "not quite",
  "wrong",
  "incorrect",
  "try again",
  "no dice",
  "nothing",
  "nothing doing",
  "not even close",
  "fat chance",
  "dream on",
  "forget it",
  "not likely",
  "unlikely",
  "not really",
  "I think not",
  "no way",
  "no way, pal",
  "not gonna happen",
  "ain't happening",
  "not in this lifetime",
  "maybe never",
  "keep dreaming",
  "nice try",
  "good try",
  "close, but no",
  "better luck next time",
  "not this time",
  "that's a no",
  "that's gonna be a no",
  "big nope",
  "huge nope",
  "definitely not",
  "certainly not",
  "absolutely positively not",
  "negative, captain",
  "negative, chief",
  "negative, ghost rider",
  "request denied",
  "access denied",
  "permission denied",
  "answer denied",
  "computer says no",
  "error: no",
  "404: yes not found",
  "zero",
  "zero chance",
  "zero luck",
  "bupkis",
  "diddly squat",
  "squat",
  "nothing at all",
  "not one bit",
  "not remotely",
  "not remotely close",
  "no sir",
  "no ma'am",
  "no thanks",
  "thanks, but no",
  "I'm good",
  "we're good",
  "I'll pass",
  "I'll decline",
  "count me out",
  "leave me out of it",
  "not interested",
  "not available",
  "unavailable",
  "invalid",
  "false",
  "false alarm",
  "incorrect answer",
  "wrong answer",
  "try something else",
  "think again",
  "guess again",
  "swing and a miss",
  "missed it",
  "not even",
  "as if",
  "in your dreams",
  "when pigs fly",
  "over my dead body"
];